package dk.kalhauge.plan.dsl.engine

import dk.kalhauge.document.dsl.file
import dk.kalhauge.document.dsl.folder
import dk.kalhauge.document.dsl.structure.Tree
import dk.kalhauge.document.dsl.structure.root

fun docs(title: String, subtitle: String, build: Tree.BaseTrunk.() -> Unit = {}) = root {
  folder("docs") {
    folder("_layouts") {
      file("default.html",
        """
        <!DOCTYPE html>
        <html lang="{{ site.lang | default: "en-US" }}">
          <head>
            <meta charset="UTF-8">
        {% seo %}
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta name="theme-color" content="#157878">
            <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
            <link rel="stylesheet" href="{{ '/assets/css/style.css?v=' | append: site.github.build_revision | relative_url }}">
          </head>
          <body>
            <header class="page-header" role="banner">
              <a style="color: cyan; text-align: left" href="#content">Skip to the content.</a>
              <h1 class="project-name">{{ page.title | default: site.title | default: site.github.repository_name }}</h1>
              <h2 class="project-tagline">
                <a href="{{ '/' | relative_url }}" style="color: white">{{ page.description | default: site.description | default: site.github.project_tagline }}</a>
              </h2>
            </header>
        
            <main id="content" class="main-content" role="main">
              {{ content }}
              <footer class="site-footer">
                <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</span>
              </footer>
            </main>
          </body>
        </html>        
        """.trimIndent()
        )
      }
    file("_config.yml",
      """
      theme: jekyll-theme-cayman
      title: {{title}}
      description: {{subtitle}}
      plugins:
        - jemoji
      """.trimIndent(),
      mapOf("title" to title, "subtitle" to subtitle)
      )
    folder("assets") {
      folder("css") {
        file("style.scss",
          """
          ---
          ---

          @import "{{ site.theme }}";
          .main-content h6 {
            margin-top: 1rem;
            margin-bottom: -1rem;
            font-size: 1.1rem;
            font-style: normal;
            font-weight: normal;
            color: black
            }
          @media screen and (min-width: 64em) {
            .main-content h6 {
              font-size:1.1rem
              }
            }
          @media screen and (min-width: 42em) and (max-width: 64em) {
            .main-content h6 {
              font-size:1.1rem
              }
            }
          @media screen and (max-width: 42em) {
            .main-content h6 {
              font-size:1rem
              }
            }
          """.trimIndent()
          )
        }
      }
    build()
    }
  }
